/**
 * Data access for the Brier UI.
 *
 * Two sources only, per the brief:
 *   1. committed JSON artifacts, served from /public/artifacts (copied
 *      unmodified from the repo's artifacts/ directory), and
 *   2. live chain reads over RPC.
 *
 * There is no database, no localStorage, and no mock data — including in
 * loading and error states. If an artifact is missing or an RPC call fails,
 * the caller receives an explicit failure it must render as such. Nothing here
 * ever substitutes a plausible-looking value for a real one.
 */

export type Load<T> =
  | { state: 'loading' }
  | { state: 'ok'; data: T }
  | { state: 'missing'; what: string; detail: string };

// ---------------------------------------------------------------------
// artifact shapes (only the fields the UI reads)
// ---------------------------------------------------------------------

export interface ReliabilityBin {
  bin_lo: number;
  bin_hi: number;
  count: number;
  mean_conf: number | null;
  empirical_freq: number | null;
}

export interface Phase1Report {
  n_test: number;
  temperature: number;
  mlp_parameters: number;
  base_accuracy_train: number;
  base_accuracy_test: number;
  ece: Record<string, number>;
  mce: Record<string, number>;
  brier: Record<string, number>;
  reliability_uncalibrated: ReliabilityBin[];
  reliability_temperature: ReliabilityBin[];
  features: string[];
}

export interface MultiseedSummaryEntry {
  mean: number;
  std: number;
  min: number;
  max: number;
  n: number;
}

export interface MultiseedReport {
  seeds: number[];
  n_seeds: number;
  summary: {
    ece: Record<string, MultiseedSummaryEntry>;
    brier: Record<string, MultiseedSummaryEntry>;
    accuracy: Record<string, MultiseedSummaryEntry>;
    temperature: MultiseedSummaryEntry;
  };
  significance: Record<
    string,
    { statistic: number | null; p_value: number; median_difference?: number }
  >;
  temperature_beats_mlp_on_ece_in_n_seeds: number;
  control_worse_than_uncalibrated_in_n_seeds: number;
}

export interface ShapAttribution {
  feature: string;
  shap: number;
  direction: 'toward_reject' | 'toward_approve';
}

export interface DecisionRecord {
  index: number;
  margin: number;
  label: number;
  top5: ShapAttribution[];
  canonical: [string, string][];
}

export interface SweepRecord {
  name: string;
  n_params: number;
  logrows?: number;
  num_rows_used?: number;
  prove_s?: number;
  proof_bytes?: number;
  test_ece?: number;
  verify_ok?: boolean;
}

export interface SweepReport {
  records: SweepRecord[];
  distinct_logrows: number[];
  logrows_constant: boolean;
}

export interface GasReport {
  gas: Record<string, number>;
  notes: string[];
}

export interface Phase3Report {
  ezkl_version: string;
  metrics: Record<string, string>;
  temperature_head: Record<string, unknown>;
}

export interface ScenarioRecord {
  name: string;
  row: number;
  confidence: number;
  outcome: string;
  slash_wei: number;
  slash_pct: number;
  prove_s: number;
  decision: string;
  ground_truth: string;
}

export interface Phase5Report {
  scenarios: ScenarioRecord[];
  ordering_holds: boolean;
  notes: string[];
}

// ---------------------------------------------------------------------
// loader
// ---------------------------------------------------------------------

/**
 * Fetch a committed artifact.
 *
 * A missing or malformed artifact resolves to `missing` carrying the real
 * reason. It never resolves to a fabricated default — a UI that invents a
 * number when the file is absent is worse than one that shows nothing.
 */
export async function loadArtifact<T>(file: string, label: string): Promise<Load<T>> {
  try {
    const res = await fetch(`/artifacts/${file}`, { cache: 'no-store' });
    if (!res.ok) {
      return {
        state: 'missing',
        what: label,
        detail: `artifacts/${file} returned HTTP ${res.status}. Regenerate it by running the pipeline scripts in the repository root.`,
      };
    }
    return { state: 'ok', data: (await res.json()) as T };
  } catch (err) {
    return {
      state: 'missing',
      what: label,
      detail: `artifacts/${file} could not be read (${
        err instanceof Error ? err.message : 'unknown error'
      }). It is generated by the repo's pipeline and is not committed as a placeholder.`,
    };
  }
}

// ---------------------------------------------------------------------
// formatting — every helper preserves precision; none rounds for looks
// ---------------------------------------------------------------------

export const fmt = {
  /** Fixed decimals. Never trims significant digits to look tidier. */
  dec: (v: number, places = 4) => v.toFixed(places),
  /** Thousands separators for gas and byte counts. */
  int: (v: number) => v.toLocaleString('en-US'),
  pct: (v: number, places = 2) => `${v.toFixed(places)}%`,
  /** wei -> ETH, at full precision. */
  eth: (wei: number, places = 6) => (wei / 1e18).toFixed(places),
  seconds: (s: number, places = 2) => `${s.toFixed(places)} s`,
};

/** The label the project itself uses for a value it has not measured. */
export const NOT_MEASURED = 'not measured';
